### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by wamry** [kisom/ctrans#2]
I ran the command `./ctrans.py -s vol_reference.js -o utf-8 -e utf-8 -t`

I got the output 

> Traceback (most recent call last):
>   File "./ctrans.py", line 326, in <module>
>     scan_file(target)
>   File "./ctrans.py", line 252, in scan_file
>     writer.write(tcode.decode('utf-8'))
> UnboundLocalError: local variable 'tcode' referenced before assignment

**Comment by zlyxm** [comment]
There is no .js in the translatable file extension
File "./ctrans.py", line 48
